Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "ubuntu2004"
  config.vm.define "uulm-zoom-ubuntu2004"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "UUlm Zoom Ubuntu 20.04"
    vb.memory = "8192"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--usb", "on"]

    #add USB device to VM. Check vendor and product ID with VBoxManage list usbhost
    #vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'ESP', '--vendorid', '0x1a86', '--productid', '0x7523']

    vb.customize ["modifyvm", :id, "--audio", "alsa"]
    vb.customize ["modifyvm", :id, "--audioout", "on"]
    vb.customize ["modifyvm", :id, "--audioin", "on"]
    
    vb.gui = true
  end

  config.vm.provision "file", source: "scripts/.", destination: "/tmp/provision/"
  $script = "/bin/bash --login /tmp/provision/provision.sh"
  config.vm.provision :shell, privileged: false, inline: $script, run: "once"
end
